"""vast.ai entrypoint: provision a GPU instance and run MyOwnTransformer jobs on it.

Replaces the old Modal setup. One-time setup:
    pip install vastai python-dotenv
    echo 'VAST_AI_API_KEY=...' >> .env.local   # key from https://cloud.vast.ai/manage-keys/

The module keeps track of one "current" instance in .vast_instance.json so the
commands chain naturally:

    python vast_train.py offers                          # browse cheap GPU offers
    python vast_train.py create                          # provision + wait for SSH
    python vast_train.py push                            # rsync code + data up
    python vast_train.py prepare                         # build tokenizer + .bin shards
    python vast_train.py train --epochs 2                # pretrain (streams logs)
    python vast_train.py train --detach                  #   ... or in background
    python vast_train.py sft-prepare
    python vast_train.py sft --checkpoint saved/vast_run/ckpt_final.pt
    python vast_train.py dpo-prepare
    python vast_train.py dpo --checkpoint saved/vast_run_sft/sft_final.pt
    python vast_train.py pull                            # rsync saved/ back to ./vast_out/
    python vast_train.py destroy                         # stop billing

    python vast_train.py pipeline                        # the whole chain, detached
    ./watch_pipeline.sh                                  # launch + watch + auto-pull

    python vast_train.py smoke                           # end-to-end sanity check
"""
import argparse
import json
import os
import subprocess
import sys
import time

from dotenv import load_dotenv

# torch 2.11 matches what we run locally; torch.optim.Muon needs >= 2.9.
IMAGE = "pytorch/pytorch:2.11.0-cuda12.8-cudnn9-runtime"
REMOTE_ROOT = "/root/myowntransformer"
DATA_DIR = "data_cache/cosmopedia"  # relative to REMOTE_ROOT, mirrors repo layout
STATE_FILE = ".vast_instance.json"
PULL_DIR = "vast_out"

# Cheap-first defaults for real runs; smoke clamps price harder.
# compute_cap>=750 keeps us on GPUs torch 2.11 ships kernels for (sm_75+).
DEFAULT_QUERY = ("gpu_ram>=20 cuda_max_good>=12.8 num_gpus=1 compute_cap>=750 "
                 "rentable=true reliability>=0.95 inet_down>=300")
SMOKE_QUERY = ("gpu_ram>=10 cuda_max_good>=12.8 num_gpus=1 compute_cap>=750 "
               "rentable=true dph<=0.5 reliability>=0.9 verified=true inet_down>=300")

SSH_OPTS = [
    "-o", "StrictHostKeyChecking=no",
    "-o", "UserKnownHostsFile=/dev/null",
    "-o", "ConnectTimeout=15",
    "-o", "LogLevel=ERROR",
]

RSYNC_EXCLUDES = [
    ".git", ".claude", "__pycache__", "**/__pycache__", ".pytest_cache",
    "chat/target", "saved", "modal_out", "vast_out", "data_cache/local_chat",
    ".env.local", STATE_FILE, "watch_pipeline.log", ".DS_Store",
]

PIPELINE_SCRIPT = r"""#!/bin/bash
# Generated by vast_train.py pipeline — resumable chain: prepare -> pretrain -> sft.
set -uo pipefail
cd {root}
export MPLBACKEND=Agg
{hf_export}
DATA={data_dir}
DIR="{dir_name}"
SFT="{sft_dir_name}"
DPO="{dpo_dir_name}"
step() {{ echo "[pipeline $(date +%H:%M:%S)] $*"; }}

if [ ! -f "$DATA/train.bin" ]; then
  step "prepare"
  python -u prepare.py --output-dir "$DATA" {prepare_args} || exit 1
fi

if [ ! -f "saved/$DIR/ckpt_final.pt" ]; then
  # Resume weights from the newest periodic checkpoint if one survived a
  # previous attempt (LR schedule restarts, which is fine).
  latest=$(ls "saved/$DIR"/ckpt_step*.pt 2>/dev/null | sed 's/.*ckpt_step//; s/\.pt//' | sort -n | tail -1)
  extra=""
  if [ -n "$latest" ]; then
    extra="-loadname saved/$DIR/ckpt_step$latest.pt"
    step "resuming pretrain from $extra"
  fi
  step "pretrain"
  python -u train.py -data_dir "$DATA" -dir_name "$DIR" {train_args} $extra || exit 1
fi

if [ ! -f "$DATA/sft_train.bin" ]; then
  step "sft_prepare"
  python -u sft_prepare.py --output-dir "$DATA" || exit 1
fi

if [ ! -f "saved/$SFT/sft_final.pt" ]; then
  step "sft"
  python -u finetune.py --checkpoint "saved/$DIR/ckpt_final.pt" --data-dir "$DATA" \
    --dir-name "$SFT" {sft_args} || exit 1
fi

if [ ! -f "$DATA/dpo_train.bin" ]; then
  step "dpo_prepare"
  python -u dpo_prepare.py --output-dir "$DATA" || exit 1
fi

if [ ! -f "saved/$DPO/dpo_final.pt" ]; then
  step "dpo"
  python -u dpo.py --checkpoint "saved/$SFT/sft_final.pt" --data-dir "$DATA" \
    --dir-name "$DPO" {dpo_args} || exit 1
fi

echo "PIPELINE COMPLETE"
"""


# --------------------------------------------------------------------------
# client + state
# --------------------------------------------------------------------------

def get_client():
    from vastai import VastAI
    key = os.environ.get("VAST_API_KEY") or os.environ.get("VAST_AI_API_KEY")
    if not key:
        sys.exit("no VAST_API_KEY or VAST_AI_API_KEY in env or .env.local — "
                 "get one at https://cloud.vast.ai/manage-keys/")
    os.environ["VAST_API_KEY"] = key
    return VastAI(api_key=key)


def hf_env():
    """HF_TOKEN raises HuggingFace streaming rate limits for prepare/sft_prepare."""
    tok = os.environ.get("HF_TOKEN", "")
    return f"HF_TOKEN={tok} " if tok else ""


def load_state(required=True):
    if not os.path.exists(STATE_FILE):
        if required:
            sys.exit(f"no {STATE_FILE} — run `python vast_train.py create` first")
        return None
    with open(STATE_FILE) as f:
        return json.load(f)


def save_state(state):
    with open(STATE_FILE, "w") as f:
        json.dump(state, f, indent=2)


def clear_state():
    if os.path.exists(STATE_FILE):
        os.remove(STATE_FILE)


# --------------------------------------------------------------------------
# ssh / rsync helpers
# --------------------------------------------------------------------------

def ssh_prefix(state):
    return ["ssh", f"-p{state['ssh_port']}", *SSH_OPTS, f"root@{state['ssh_host']}"]


def run_remote(state, cmd, check=True):
    """Run a shell command on the instance, streaming output."""
    return subprocess.run(ssh_prefix(state) + [cmd], check=check)


def rsync(state, src, dst, extra_excludes=()):
    ssh_expr = " ".join(["ssh", f"-p{state['ssh_port']}", *SSH_OPTS])
    cmd = ["rsync", "-az", "-e", ssh_expr]
    for pat in list(RSYNC_EXCLUDES) + list(extra_excludes):
        cmd += ["--exclude", pat]
    cmd += [src, dst]
    subprocess.run(cmd, check=True)


def wait_ready(client, instance_id, timeout=12 * 60):
    """Wait for the instance to report running, then for SSH to answer."""
    deadline = time.time() + timeout
    last = None
    while time.time() < deadline:
        info = client.show_instance(id=instance_id) or {}
        status = info.get("actual_status") or info.get("status") or "?"
        if status != last:
            print(f"  instance {instance_id}: {status}", flush=True)
            last = status
        if status == "running":
            state = {
                "id": instance_id,
                "ssh_host": info.get("ssh_host") or info.get("public_ipaddr"),
                "ssh_port": info.get("ssh_port", 22),
                "gpu": info.get("gpu_name"),
                "dph": info.get("dph_total"),
            }
            # sshd can lag the status flip; probe until it answers.
            probe_deadline = time.time() + 4 * 60
            while time.time() < probe_deadline:
                rc = subprocess.run(
                    ssh_prefix(state) + ["true"],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                ).returncode
                if rc == 0:
                    return state
                time.sleep(5)
            raise RuntimeError(f"instance {instance_id} is running but SSH never came up")
        time.sleep(10)
    raise RuntimeError(f"instance {instance_id} not running after {timeout // 60} min "
                       f"(last status: {last})")


def pick_offer(client, query, limit=10):
    offers = client.search_offers(query=query, order="dph_total", limit=limit)
    if not offers:
        sys.exit(f"no offers match: {query}")
    return offers


def print_offers(offers):
    print(f"{'id':>10}  {'gpu':<16} {'ram(GB)':>7} {'$/hr':>7} {'down(Mbps)':>10}  {'cuda':<5} {'reliab':>6}  location")
    for o in offers:
        print(f"{o.get('id'):>10}  {str(o.get('gpu_name')):<16} "
              f"{o.get('gpu_ram', 0):>7.0f} {o.get('dph_total', 0):>7.3f} "
              f"{o.get('inet_down', 0):>10.0f}  {o.get('cuda_max_good', 0):<5.1f} "
              f"{o.get('reliability2', 0):>6.3f}  {o.get('geolocation', '?')}")


# --------------------------------------------------------------------------
# commands
# --------------------------------------------------------------------------

def cmd_offers(args):
    client = get_client()
    print_offers(pick_offer(client, args.query, limit=args.limit))


def cmd_create(args):
    client = get_client()
    offers = pick_offer(client, args.query, limit=10)
    print_offers(offers[:5])
    offer = next((o for o in offers if o.get("id") == args.offer_id), None) \
        if args.offer_id else offers[0]
    print(f"creating instance from offer {offer['id']} "
          f"({offer.get('gpu_name')}, ~${offer.get('dph_total', 0):.3f}/hr)...")
    resp = client.create_instance(
        id=offer["id"], image=args.image, disk=args.disk,
        label=args.label, runtype="ssh",
    )
    instance_id = resp.get("new_contract") or resp.get("id")
    if not instance_id:
        sys.exit(f"create failed: {resp}")
    print(f"instance {instance_id} created; waiting for it to come up...")

    pub = os.path.expanduser(os.environ.get("VAST_SSH_PUBKEY", "~/.ssh/id_ed25519.pub"))
    with open(pub) as f:
        client.attach_ssh(instance_id, f.read().strip())

    try:
        state = wait_ready(client, instance_id)
    except RuntimeError as e:
        sys.exit(f"{e}\ninstance {instance_id} may still be loading — check "
                 f"`python vast_train.py status --id {instance_id}`, or destroy "
                 f"with `python vast_train.py destroy --id {instance_id}`")
    state["label"] = args.label
    save_state(state)
    print(f"ssh ready: root@{state['ssh_host']} -p {state['ssh_port']} "
          f"({state.get('gpu')}, ~${(state.get('dph') or 0):.3f}/hr)")

    print("bootstrapping python deps (datasets, matplotlib)...")
    run_remote(state, "pip install -q --break-system-packages datasets matplotlib")
    print("instance ready — next: `python vast_train.py push`")


def cmd_push(args):
    state = load_state()
    run_remote(state, f"mkdir -p {REMOTE_ROOT}")
    rsync(state, "./", f"root@{state['ssh_host']}:{REMOTE_ROOT}/")
    print(f"pushed repo -> {REMOTE_ROOT}")


def cmd_ssh(args):
    state = load_state()
    if not args.cmd:
        print(" ".join(ssh_prefix(state)))
        return
    sys.exit(run_remote(state, " ".join(args.cmd), check=False).returncode)


def cmd_prepare(args):
    state = load_state()
    if not args.force:
        rc = run_remote(state, f"test -f {REMOTE_ROOT}/{DATA_DIR}/train.bin", check=False).returncode
        if rc == 0:
            print("train.bin already exists on the instance (pass --force to rebuild)")
            return
    cmd = (f"cd {REMOTE_ROOT} && {hf_env()}python -u prepare.py --output-dir {DATA_DIR} "
           f"--vocab-size {args.vocab_size} --bpe-train-docs {args.bpe_train_docs} "
           f"--holdout-period {args.holdout_period}")
    if args.max_train_docs > 0:
        cmd += f" --max-train-docs {args.max_train_docs}"
    run_remote(state, cmd)


def cmd_train(args):
    state = load_state()
    cmd = (f"cd {REMOTE_ROOT} && MPLBACKEND=Agg {hf_env()}python -u train.py "
           f"-data_dir {DATA_DIR} -dir_name {args.dir_name} "
           f"-d_model {args.d_model} -n_layers {args.n_layers} -heads {args.heads} "
           f"-kv_heads {args.kv_heads} -loops {args.loops} "
           f"-batchsize {args.batchsize} -grad_accum {args.grad_accum} "
           f"-seqlen {args.seqlen} -epochs {args.epochs} "
           f"-lr {args.lr} -muon_lr {args.muon_lr} -warmup_steps {args.warmup_steps} "
           f"-save_every {args.save_every} -val_every {args.val_every} "
           f"-early_stop {args.early_stop} -early_stop_delta {args.early_stop_delta} "
           f"-early_stop_cooldown {args.early_stop_cooldown} "
           f"-printevery {args.printevery}")
    if args.loadname:
        cmd += f" -loadname {args.loadname}"
    if args.detach:
        run_remote(state, f"nohup {cmd} > train_{args.dir_name}.log 2>&1 & echo detached pid $!")
        print(f"detached; watch with `python vast_train.py ssh tail -f train_{args.dir_name}.log`")
    else:
        run_remote(state, cmd)


def cmd_sft_prepare(args):
    state = load_state()
    if not args.force:
        rc = run_remote(state, f"test -f {REMOTE_ROOT}/{DATA_DIR}/sft_train.bin", check=False).returncode
        if rc == 0:
            print("sft_train.bin already exists on the instance (pass --force to rebuild)")
            return
    cmd = (f"cd {REMOTE_ROOT} && {hf_env()}python -u sft_prepare.py --output-dir {DATA_DIR} "
           f"--holdout-period {args.holdout_period}")
    if args.max_conversations > 0:
        cmd += f" --max-conversations {args.max_conversations}"
    run_remote(state, cmd)


def cmd_sft(args):
    state = load_state()
    cmd = (f"cd {REMOTE_ROOT} && MPLBACKEND=Agg {hf_env()}python -u finetune.py "
           f"--checkpoint {args.checkpoint} --data-dir {DATA_DIR} "
           f"--epochs {args.epochs} --batchsize {args.batchsize} --seqlen {args.seqlen} "
           f"--lr {args.lr} --muon-lr {args.muon_lr} --warmup-steps {args.warmup_steps} "
           f"--save-every {args.save_every} --val-every {args.val_every} "
           f"--dir-name {args.dir_name}")
    if args.detach:
        run_remote(state, f"nohup {cmd} > sft_{args.dir_name}.log 2>&1 & echo detached pid $!")
        print(f"detached; watch with `python vast_train.py ssh tail -f sft_{args.dir_name}.log`")
    else:
        run_remote(state, cmd)


def cmd_dpo_prepare(args):
    state = load_state()
    if not args.force:
        rc = run_remote(state, f"test -f {REMOTE_ROOT}/{DATA_DIR}/dpo_train.bin", check=False).returncode
        if rc == 0:
            print("dpo_train.bin already exists on the instance (pass --force to rebuild)")
            return
    cmd = (f"cd {REMOTE_ROOT} && {hf_env()}python -u dpo_prepare.py --output-dir {DATA_DIR} "
           f"--holdout-period {args.holdout_period}")
    if args.max_pairs > 0:
        cmd += f" --max-pairs {args.max_pairs}"
    run_remote(state, cmd)


def cmd_dpo(args):
    state = load_state()
    cmd = (f"cd {REMOTE_ROOT} && MPLBACKEND=Agg {hf_env()}python -u dpo.py "
           f"--checkpoint {args.checkpoint} --data-dir {DATA_DIR} "
           f"--epochs {args.epochs} --batchsize {args.batchsize} --beta {args.beta} "
           f"--lr {args.lr} --muon-lr {args.muon_lr} --warmup-steps {args.warmup_steps} "
           f"--save-every {args.save_every} --val-every {args.val_every} "
           f"--dir-name {args.dir_name}")
    if args.detach:
        run_remote(state, f"nohup {cmd} > dpo_{args.dir_name}.log 2>&1 & echo detached pid $!")
        print(f"detached; watch with `python vast_train.py ssh tail -f dpo_{args.dir_name}.log`")
    else:
        run_remote(state, cmd)


def cmd_pipeline(args):
    state = load_state()
    script = PIPELINE_SCRIPT.format(
        root=REMOTE_ROOT,
        data_dir=DATA_DIR,
        dir_name=args.dir_name,
        sft_dir_name=args.sft_dir_name,
        hf_export=(f"export HF_TOKEN={os.environ['HF_TOKEN']}"
                   if os.environ.get("HF_TOKEN") else ""),
        prepare_args=(f"--max-train-docs {args.max_train_docs}" if args.max_train_docs > 0 else ""),
        train_args=(f"-d_model {args.d_model} -n_layers {args.n_layers} -heads {args.heads} "
                    f"-kv_heads {args.kv_heads} -loops {args.loops} "
                    f"-batchsize {args.batchsize} -grad_accum {args.grad_accum} "
                    f"-seqlen {args.seqlen} -epochs {args.epochs} "
                    f"-lr {args.lr} -muon_lr {args.muon_lr} -warmup_steps {args.warmup_steps} "
                    f"-save_every {args.save_every} -val_every {args.val_every} "
                    f"-early_stop {args.early_stop} -early_stop_delta {args.early_stop_delta} "
                    f"-early_stop_cooldown {args.early_stop_cooldown}"),
        sft_args=f"--epochs {args.sft_epochs}",
        dpo_dir_name=args.dpo_dir_name,
        dpo_args=(f"--epochs {args.dpo_epochs} --batchsize {args.dpo_batchsize} "
                  f"--beta {args.dpo_beta} --lr {args.dpo_lr} --muon-lr {args.dpo_muon_lr}"),
    )
    subprocess.run(ssh_prefix(state) + [f"cat > {REMOTE_ROOT}/remote_pipeline.sh"],
                   input=script.encode(), check=True)
    run_remote(state, f"cd {REMOTE_ROOT} && nohup bash remote_pipeline.sh > pipeline.log 2>&1 & "
                      "echo pipeline detached pid $!")
    print("pipeline running server-side (survives laptop sleep). "
          "Watch with ./watch_pipeline.sh or `python vast_train.py status`")


def cmd_status(args):
    client = get_client()
    state = load_state(required=False) or {}
    instance_id = args.id or state.get("id")
    if not instance_id:
        sys.exit("no current instance — pass --id or run create first")
    info = client.show_instance(id=instance_id) or {}
    print(f"instance {instance_id}: {info.get('actual_status', '?')} "
          f"{info.get('gpu_name', '')} ~${info.get('dph_total', 0):.3f}/hr")
    state = state if state.get("id") == instance_id else {
        "id": instance_id,
        "ssh_host": info.get("ssh_host") or info.get("public_ipaddr"),
        "ssh_port": info.get("ssh_port", 22),
    }
    if info.get("actual_status") == "running":
        run_remote(state, f"cd {REMOTE_ROOT} && "
                          "(tail -n 20 pipeline.log 2>/dev/null || true) && echo --- && "
                          "(ls saved/*/ 2>/dev/null || echo 'no checkpoints yet')",
                   check=False)


def cmd_pull(args):
    state = load_state()
    os.makedirs(args.out, exist_ok=True)
    rsync(state, f"root@{state['ssh_host']}:{REMOTE_ROOT}/saved/", f"{args.out}/saved/")
    print(f"pulled saved/ -> {args.out}/saved/")
    ssh_expr = " ".join(["ssh", f"-p{state['ssh_port']}", *SSH_OPTS])
    for f in [f"{DATA_DIR}/tokenizer.json", "pipeline.log", "learning_curves.png"]:
        rc = subprocess.run(
            ["rsync", "-az", "-e", ssh_expr,
             f"root@{state['ssh_host']}:{REMOTE_ROOT}/{f}", f"{args.out}/"],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        ).returncode
        if rc == 0:
            print(f"pulled {f}")
    print(f"artifacts in ./{args.out}/")


def cmd_destroy(args):
    client = get_client()
    state = load_state(required=False) or {}
    instance_id = args.id or state.get("id")
    if not instance_id:
        sys.exit("no current instance — pass --id")
    client.destroy_instance(id=instance_id)
    print(f"destroyed instance {instance_id}")
    if state.get("id") == instance_id:
        clear_state()


def cmd_smoke(args):
    """End-to-end check: cheapest GPU -> CUDA test -> tiny train -> pull -> destroy."""
    client = get_client()
    instance_id = None
    state = None
    t0 = time.time()
    try:
        print("[smoke] searching offers...")
        offer = pick_offer(client, SMOKE_QUERY, limit=5)[0]
        print(f"[smoke] offer {offer['id']}: {offer.get('gpu_name')} "
              f"@ ~${offer.get('dph_total', 0):.3f}/hr")
        resp = client.create_instance(id=offer["id"], image=IMAGE, disk=25,
                                      label="mot-smoke", runtype="ssh")
        instance_id = resp.get("new_contract") or resp.get("id")
        if not instance_id:
            sys.exit(f"[smoke] create failed: {resp}")
        pub = os.path.expanduser(os.environ.get("VAST_SSH_PUBKEY", "~/.ssh/id_ed25519.pub"))
        with open(pub) as f:
            client.attach_ssh(instance_id, f.read().strip())
        state = wait_ready(client, instance_id, timeout=20 * 60)
        save_state(state)

        print("[smoke] GPU + torch check...")
        run_remote(state, "nvidia-smi --query-gpu=name,memory.total --format=csv,noheader && "
                          "python -c \"import torch; a=torch.randn(2048,2048,device='cuda'); "
                          "print('torch', torch.__version__, '| cuda ok:', bool((a@a).sum()))\"")

        print("[smoke] pushing repo...")
        run_remote(state, f"mkdir -p {REMOTE_ROOT}")
        rsync(state, "./", f"root@{state['ssh_host']}:{REMOTE_ROOT}/")

        print("[smoke] tiny train (synthetic shards, ~400 steps on GPU)...")
        run_remote(state, "pip install -q --break-system-packages matplotlib")  # train.py imports it
        gen_bins = (
            f"cd {REMOTE_ROOT} && python -c \""
            "import os, numpy as np; "
            "from tokenizer import BPETokenizer; "
            "d='data_cache/smoke'; os.makedirs(d, exist_ok=True); "
            "t=BPETokenizer(); t.load('data_cache/cosmopedia/tokenizer.json'); "
            "[np.random.randint(0, t.vocab_size, 200_000).astype(np.uint16).tofile(f'{d}/{n}.bin') "
            "for n in ('train','val','test')]; "
            "os.link('data_cache/cosmopedia/tokenizer.json', f'{d}/tokenizer.json'); "
            "print('synthetic shards ready, vocab', t.vocab_size)\""
        )
        run_remote(state, gen_bins)
        run_remote(state, f"cd {REMOTE_ROOT} && MPLBACKEND=Agg python -u train.py "
                          "-data_dir data_cache/smoke -d_model 64 -n_layers 2 -heads 2 "
                          "-batchsize 8 -seqlen 64 -epochs 1 -warmup_steps 5 "
                          "-save_every 0 -val_every 0 -printevery 100 -dir_name smoke")

        print("[smoke] pulling checkpoint back...")
        os.makedirs(f"{args.out}/smoke", exist_ok=True)
        rsync(state, f"root@{state['ssh_host']}:{REMOTE_ROOT}/saved/smoke/", f"{args.out}/smoke/")
        assert os.path.exists(f"{args.out}/smoke/ckpt_final.pt"), "ckpt_final.pt missing after pull"
        print(f"[smoke] PASS in {(time.time() - t0) / 60:.1f} min — "
              f"checkpoint at {args.out}/smoke/ckpt_final.pt")
    finally:
        if instance_id and not args.keep:
            print("[smoke] destroying instance...")
            try:
                client.destroy_instance(id=instance_id)
            except Exception as e:
                print(f"[smoke] WARNING: destroy failed for {instance_id}: {e} — "
                      "destroy it manually at https://cloud.vast.ai/instances/")
            clear_state()
        elif instance_id:
            print(f"[smoke] --keep: instance {instance_id} left running "
                  "(destroy with `python vast_train.py destroy`)")


# --------------------------------------------------------------------------
# argparse
# --------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("offers", help="list cheapest matching GPU offers")
    sp.add_argument("--query", default=DEFAULT_QUERY)
    sp.add_argument("--limit", type=int, default=10)
    sp.set_defaults(fn=cmd_offers)

    sp = sub.add_parser("create", help="provision an instance and wait for SSH")
    sp.add_argument("--query", default=DEFAULT_QUERY)
    sp.add_argument("--offer-id", type=int, default=None, help="use a specific offer id")
    sp.add_argument("--image", default=IMAGE)
    sp.add_argument("--disk", type=float, default=80,
                    help="GB; ~8B-token pretrain shards + checkpoints need >40")
    sp.add_argument("--label", default="myowntransformer")
    sp.set_defaults(fn=cmd_create)

    sub.add_parser("push", help="rsync code + data to the instance").set_defaults(fn=cmd_push)

    sp = sub.add_parser("ssh", help="print the ssh command, or run a remote command")
    sp.add_argument("cmd", nargs=argparse.REMAINDER)
    sp.set_defaults(fn=cmd_ssh)

    sp = sub.add_parser("prepare", help="build tokenizer + .bin shards on the instance")
    sp.add_argument("--force", action="store_true")
    sp.add_argument("--vocab-size", type=int, default=32000)
    sp.add_argument("--bpe-train-docs", type=int, default=10000)
    sp.add_argument("--max-train-docs", type=int, default=0)
    sp.add_argument("--holdout-period", type=int, default=500)
    sp.set_defaults(fn=cmd_prepare)

    sp = sub.add_parser("train", help="pretrain on the instance (~98M defaults)")
    sp.add_argument("--d-model", type=int, default=640)
    sp.add_argument("--n-layers", type=int, default=17)
    sp.add_argument("--heads", type=int, default=10)
    sp.add_argument("--kv-heads", type=int, default=5)
    sp.add_argument("--loops", type=int, default=1)
    sp.add_argument("--batchsize", type=int, default=128)
    sp.add_argument("--grad-accum", type=int, default=1)
    sp.add_argument("--seqlen", type=int, default=1024)
    sp.add_argument("--epochs", type=int, default=1)
    sp.add_argument("--lr", type=float, default=3e-4)
    sp.add_argument("--muon-lr", type=float, default=0.03)
    sp.add_argument("--warmup-steps", type=int, default=1000)
    sp.add_argument("--save-every", type=int, default=2000)
    sp.add_argument("--val-every", type=int, default=2000)
    sp.add_argument("--early-stop", type=int, default=0,
                    help="early-stop patience in val evals (0 = disabled)")
    sp.add_argument("--early-stop-delta", type=float, default=0.005)
    sp.add_argument("--early-stop-cooldown", type=int, default=300)
    sp.add_argument("--printevery", type=int, default=50)
    sp.add_argument("--dir-name", default="vast_run")
    sp.add_argument("--loadname", default="")
    sp.add_argument("--detach", action="store_true")
    sp.set_defaults(fn=cmd_train)

    sp = sub.add_parser("sft-prepare", help="tokenize chat SFT data on the instance")
    sp.add_argument("--force", action="store_true")
    sp.add_argument("--max-conversations", type=int, default=0)
    sp.add_argument("--holdout-period", type=int, default=200)
    sp.set_defaults(fn=cmd_sft_prepare)

    sp = sub.add_parser("sft", help="fine-tune a checkpoint on chat data")
    sp.add_argument("--checkpoint", required=True,
                    help="path on the instance, e.g. saved/vast_run/ckpt_final.pt")
    sp.add_argument("--epochs", type=int, default=2)
    sp.add_argument("--batchsize", type=int, default=64)
    sp.add_argument("--seqlen", type=int, default=512)
    sp.add_argument("--lr", type=float, default=3e-5)
    sp.add_argument("--muon-lr", type=float, default=0.003)
    sp.add_argument("--warmup-steps", type=int, default=100)
    sp.add_argument("--save-every", type=int, default=1000)
    sp.add_argument("--val-every", type=int, default=500)
    sp.add_argument("--dir-name", default="sft_run")
    sp.add_argument("--detach", action="store_true")
    sp.set_defaults(fn=cmd_sft)

    sp = sub.add_parser("dpo-prepare", help="tokenize DPO preference pairs on the instance")
    sp.add_argument("--force", action="store_true")
    sp.add_argument("--max-pairs", type=int, default=0)
    sp.add_argument("--holdout-period", type=int, default=200)
    sp.set_defaults(fn=cmd_dpo_prepare)

    sp = sub.add_parser("dpo", help="DPO on top of an SFT checkpoint")
    sp.add_argument("--checkpoint", required=True,
                    help="path on the instance, e.g. saved/vast_run_sft/sft_final.pt")
    sp.add_argument("--epochs", type=int, default=1)
    sp.add_argument("--batchsize", type=int, default=8, help="preference pairs per step")
    sp.add_argument("--beta", type=float, default=0.1)
    sp.add_argument("--lr", type=float, default=1e-6)
    sp.add_argument("--muon-lr", type=float, default=1e-4)
    sp.add_argument("--warmup-steps", type=int, default=100)
    sp.add_argument("--save-every", type=int, default=1000)
    sp.add_argument("--val-every", type=int, default=500)
    sp.add_argument("--dir-name", default="dpo_run")
    sp.add_argument("--detach", action="store_true")
    sp.set_defaults(fn=cmd_dpo)

    sp = sub.add_parser("pipeline", help="prepare -> pretrain -> sft -> dpo, detached + resumable (~98M defaults)")
    sp.add_argument("--dir-name", default="vast_run")
    sp.add_argument("--sft-dir-name", default="vast_run_sft")
    sp.add_argument("--max-train-docs", type=int, default=8000000,
                    help="cap on pretrain docs tokenized (0 = full stream; "
                         "default ~8M docs ≈ 8B tokens, sized for a ~7h H200 pretrain)")
    sp.add_argument("--d-model", type=int, default=640)
    sp.add_argument("--n-layers", type=int, default=17)
    sp.add_argument("--heads", type=int, default=10)
    sp.add_argument("--kv-heads", type=int, default=5)
    sp.add_argument("--loops", type=int, default=1)
    sp.add_argument("--batchsize", type=int, default=128)
    sp.add_argument("--grad-accum", type=int, default=1)
    sp.add_argument("--seqlen", type=int, default=1024)
    sp.add_argument("--epochs", type=int, default=1)
    sp.add_argument("--lr", type=float, default=3e-4)
    sp.add_argument("--muon-lr", type=float, default=0.03)
    sp.add_argument("--warmup-steps", type=int, default=1000)
    sp.add_argument("--save-every", type=int, default=4000)
    sp.add_argument("--val-every", type=int, default=2000)
    sp.add_argument("--early-stop", type=int, default=0,
                    help="early-stop patience in val evals (0 = disabled)")
    sp.add_argument("--early-stop-delta", type=float, default=0.005)
    sp.add_argument("--early-stop-cooldown", type=int, default=300)
    sp.add_argument("--sft-epochs", type=int, default=1)
    sp.add_argument("--dpo-dir-name", default="vast_run_dpo")
    sp.add_argument("--dpo-epochs", type=int, default=1)
    sp.add_argument("--dpo-batchsize", type=int, default=8)
    sp.add_argument("--dpo-beta", type=float, default=0.1)
    sp.add_argument("--dpo-lr", type=float, default=1e-6)
    sp.add_argument("--dpo-muon-lr", type=float, default=1e-4)
    sp.set_defaults(fn=cmd_pipeline)

    sp = sub.add_parser("status", help="instance status + pipeline log tail")
    sp.add_argument("--id", type=int, default=None)
    sp.set_defaults(fn=cmd_status)

    sp = sub.add_parser("pull", help="rsync checkpoints + artifacts back to ./vast_out/")
    sp.add_argument("--out", default=PULL_DIR)
    sp.set_defaults(fn=cmd_pull)

    sp = sub.add_parser("destroy", help="destroy the current instance")
    sp.add_argument("--id", type=int, default=None)
    sp.set_defaults(fn=cmd_destroy)

    sp = sub.add_parser("smoke", help="short end-to-end GPU sanity check (creates + destroys)")
    sp.add_argument("--keep", action="store_true", help="leave the instance running")
    sp.add_argument("--out", default=PULL_DIR)
    sp.set_defaults(fn=cmd_smoke)

    args = p.parse_args()
    load_dotenv(".env.local")
    args.fn(args)


if __name__ == "__main__":
    main()
